---
- name: Mask sleep and suspend targets as well as disable gdm inactive sleep
  hosts: all
  become: true

  tasks:
    - name: Mask sleep-related systemd targets
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
      loop:
        - sleep.target
        - suspend.target
        - hibernate.target
        - hybrid-sleep.target

  tasks:
    - name: Disable sleep on AC power (inactive)
      command: sudo -u gdm dbus-run-session gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type nothing

    - name: Disable sleep on battery (inactive)
      command: sudo -u gdm dbus-run-session gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type nothing

    - name: Disable sleep on battery (inactive)
      command: sudo -u gdm dbus-run-session gsettings set org.gnome.desktop.session idle-delay 0
